name: Sync LeetCode
on:
  workflow_dispatch:   # Run manually
  schedule:
    - cron: "0 0 * * *"   # Runs daily at midnight UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sync LeetCode submissions
      - name: Sync LeetCode submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: LeetCode
          verbose: true
